name: Release Drafter
on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  non_deploy_trigger:
    runs-on: ubuntu-latest
    needs: update_release_draft
    steps:
      - uses: k8sdeploy/github-action@v1
        with:
          service-namespace: k8sdeploy
          service-name: hooks-service
          k8sdeploy-key: ${{ secrets.K8SDEPLOY_KEY }}
          k8sdeploy-secret: ${{ secrets.K8SDEPLOY_SECRET }}
          k8desploy-id: ${{ secrets.K8SDEPLOY_ID }}
          image-hash: ${{ github.sha }}
          image-tag: ${{ github.ref_name }}
